name: Pyright

on:
  pull_request:
    branches: [ main ]

jobs:

  pyright:
    name: Pyright
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install pyright
        
    - name: Run Pyright
      run: pyright .